server:
  port:8888
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/s_c?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhanglingzhe0820
